version: "3.9"

services:
  # ---------- Database ----------
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # ---------- Redis ----------
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  # ---------- MailHog (captures outgoing email) ----------
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"   # Web UI → http://localhost:8025
      - "1025:1025"   # SMTP port FastAPI will talk to

  # ---------- One-shot Alembic migration ----------
  migrate:
    build: .
    depends_on: [db]
    command: >
      sh -c "sleep 5 && alembic upgrade head"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/bankdb
      REDIS_URL: redis://redis:6379/0

  # ---------- FastAPI web app ----------
  web:
    build: .
    depends_on: [db, redis, migrate, mailhog]
    restart: unless-stopped
    environment:
      # DB / cache
      DATABASE_URL: postgresql://user:password@db:5432/bankdb
      REDIS_URL: redis://redis:6379/0

      # JWT + other app secrets
      JWT_SECRET: "super-secret-jwt-key"

      # SMTP (MailHog in dev)
      SMTP_HOST: mailhog
      SMTP_PORT: 1025          # MailHog’s SMTP port
      EMAIL_FROM: "SecureBank <no-reply@securebank.local>"
      DEBUG_MODE: "true"

      # OTP expiry (optional)
      OTP_TTL_SECONDS: 300
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --proxy-headers
      --workers 2

volumes:
  pgdata:
