"""fix account_number foreign keys

Revision ID: 93d64205c3dc
Revises: b9c25e5594e3
Create Date: 2025-07-27 23:37:37.417570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d64205c3dc'
down_revision: Union[str, Sequence[str], None] = 'b9c25e5594e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposits_id'), 'deposits', ['id'], unique=False)
    op.add_column('transactions', sa.Column('from_account_number', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('to_account_number', sa.String(), nullable=True))
    op.drop_constraint(op.f('transactions_from_account_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_to_account_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'bank_accounts', ['to_account_number'], ['account_number'])
    op.create_foreign_key(None, 'transactions', 'bank_accounts', ['from_account_number'], ['account_number'])
    op.drop_column('transactions', 'to_account_id')
    op.drop_column('transactions', 'from_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('from_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('to_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_to_account_id_fkey'), 'transactions', 'bank_accounts', ['to_account_id'], ['id'])
    op.create_foreign_key(op.f('transactions_from_account_id_fkey'), 'transactions', 'bank_accounts', ['from_account_id'], ['id'])
    op.drop_column('transactions', 'to_account_number')
    op.drop_column('transactions', 'from_account_number')
    op.drop_index(op.f('ix_deposits_id'), table_name='deposits')
    op.drop_table('deposits')
    # ### end Alembic commands ###
