"""add account_type to bank_accounts

Revision ID: b9c25e5594e3
Revises: 0d8897a22db6
Create Date: 2025-06-25 21:34:22.753478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c25e5594e3'
down_revision: Union[str, Sequence[str], None] = '0d8897a22db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('account_type', sa.String(), nullable=False, server_default='savings'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_accounts', 'account_type')
    # ### end Alembic commands ###
